/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import function.Function;
import function.Validate;
import java.awt.CardLayout;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.DataProcess;

/**
 *
 * @author Tien Nguyen
 */
public class Dphong extends javax.swing.JFrame {

    /**
     * Creates new form Dphong
     */
    Validate v = new Validate();
    Function f = Hotel.f;
    private boolean b = true;
    private static int makh;
    private long NgayNhan = 0, NgayTra = 0, thoihan = 0;
    private ArrayList<Integer> maDV = new ArrayList<>();

    public Dphong() {
        initComponents();
        setSize(600, 550);

    }

    public Dphong(int x, int y) {
        initComponents();
        setSize(600, 550);
        setLocation(x - getWidth() / 2, y - getHeight() / 2);
        tfNgayNhan.setText(getDate());
//        tfPhong.setEditable(false);
        DefaultComboBoxModel boxModel = new DefaultComboBoxModel();
        for (int i = 0; i < f.getDichVu().size(); i++) {
            boxModel.addElement(f.getDichVu().get(i).getName());

        }
        cb1.setModel(boxModel);
 btnXoa.setEnabled(false);
    }

    public void getPhong(String phong, long ngayNhan, long Ngaytra) {
        tfPhong.setText(phong);
        tfPhong.setEditable(false);
        pn.updateUI();
        if (ngayNhan == 0 || Ngaytra == 0) {
            tfNgayTra.setVisible(false);
            lbNgayTra.setVisible(false);
            thoihan = f.timeFree(phong);
            if (thoihan != 0) {
                lbEndDAy.setText("Phòng " + phong + " còng trống " + thoihan + " ngày.");
            } else {
                lbEndDAy.setVisible(false);
            }
            if (thoihan == -1) {
                tfNgay.setEditable(false);
                lbEndDAy.setText("Phòng " + phong + " đã có người đặt.");
            }
        } else {
            lbtraphong2.setVisible(false);
            tfNgay.setVisible(false);
            lb1.setVisible(false);
            tfNgayNhan.setText(getDate(ngayNhan));
            tfNgayTra.setText(getDate(Ngaytra));
            this.NgayNhan = ngayNhan;
            this.NgayTra = Ngaytra;
            lbEndDAy.setVisible(false);
        }

    }

    public String getDate(long date) {
//        Date d = new Date();
        SimpleDateFormat dinhDangThoiGian = new SimpleDateFormat("dd/MM/yyyy");

        return dinhDangThoiGian.format(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn = new javax.swing.JPanel();
        datphong = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tfPhong = new javax.swing.JTextField();
        lbtraphong2 = new javax.swing.JLabel();
        tfCmnd = new javax.swing.JTextField();
        tfDT = new javax.swing.JTextField();
        tfNgay = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfNgayNhan = new javax.swing.JTextField();
        tfNgayTra = new javax.swing.JTextField();
        lbNgayTra = new javax.swing.JLabel();
        lbEndDAy = new javax.swing.JLabel();
        Themdichvu = new javax.swing.JPanel();
        btDy = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDV = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        lbNofi = new javax.swing.JLabel();
        tfPhong1 = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfCM = new javax.swing.JTextField();

        setTitle("Đặt phòng");
        setResizable(false);
        setSize(new java.awt.Dimension(577, 511));

        pn.setLayout(new java.awt.CardLayout());

        datphong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        datphong.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 457, 97, 31));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Ngày nhận phòng:");
        datphong.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 326, -1, -1));

        tfPhong.setEditable(false);
        tfPhong.setFocusTraversalPolicyProvider(true);
        datphong.add(tfPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 95, 152, 27));

        lbtraphong2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbtraphong2.setText("Đặt phòng trong:");
        datphong.add(lbtraphong2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));
        datphong.add(tfCmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 208, 310, 27));
        datphong.add(tfDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 265, 310, 27));

        tfNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNgayActionPerformed(evt);
            }
        });
        datphong.add(tfNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 393, 149, 30));
        datphong.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 71, 370, 11));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đặt Phòng");
        datphong.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 526, 60));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");
        datphong.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 93, -1, -1));

        lb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb1.setText("ngày");
        datphong.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 396, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Số Phòng:");
        datphong.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 94, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");
        datphong.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 205, 21, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Tên Khách hàng:");
        datphong.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 151, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");
        datphong.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 157, 21, -1));
        datphong.add(tfTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 151, 310, 27));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Số CMND:");
        datphong.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 208, -1, -1));

        jButton1.setText("Đặt Phòng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        datphong.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 457, 97, 31));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Số điện thoại:");
        datphong.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 265, -1, -1));

        tfNgayNhan.setEditable(false);
        datphong.add(tfNgayNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 326, 310, 27));

        tfNgayTra.setEditable(false);
        datphong.add(tfNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 310, 30));

        lbNgayTra.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbNgayTra.setText("Ngày Trả Phòng: ");
        datphong.add(lbNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        lbEndDAy.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbEndDAy.setForeground(new java.awt.Color(255, 0, 0));
        lbEndDAy.setText("jLabel7");
        datphong.add(lbEndDAy, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 310, 18));

        pn.add(datphong, "card2");

        btDy.setText("Đồng ý");
        btDy.setEnabled(false);
        btDy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDyActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Thêm dịch vụ");

        jButton3.setText("Thoát");
        jButton3.setPreferredSize(new java.awt.Dimension(70, 27));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lstDV.setToolTipText("Các dịch vụ đã chọn");
        jScrollPane1.setViewportView(lstDV);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Phòng:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Tên:");

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("CMND:");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("Dịch vụ");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lbNofi.setBackground(new java.awt.Color(255, 0, 0));
        lbNofi.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbNofi.setForeground(new java.awt.Color(255, 0, 0));

        tfPhong1.setEditable(false);

        tfName.setEditable(false);
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        tfCM.setEditable(false);
        tfCM.setAutoscrolls(false);

        javax.swing.GroupLayout ThemdichvuLayout = new javax.swing.GroupLayout(Themdichvu);
        Themdichvu.setLayout(ThemdichvuLayout);
        ThemdichvuLayout.setHorizontalGroup(
            ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemdichvuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(ThemdichvuLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jSeparator2)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemdichvuLayout.createSequentialGroup()
                .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThemdichvuLayout.createSequentialGroup()
                        .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThemdichvuLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCM, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)))
                            .addGroup(ThemdichvuLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemdichvuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem)
                            .addComponent(btnXoa))))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemdichvuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemdichvuLayout.createSequentialGroup()
                        .addComponent(lbNofi, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemdichvuLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btDy, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))))
        );

        ThemdichvuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfCM, tfName, tfPhong1});

        ThemdichvuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnThem, btnXoa});

        ThemdichvuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btDy, jButton3});

        ThemdichvuLayout.setVerticalGroup(
            ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThemdichvuLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNofi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ThemdichvuLayout.createSequentialGroup()
                        .addComponent(tfPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addComponent(tfCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ThemdichvuLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel17)))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem)
                    .addGroup(ThemdichvuLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ThemdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btDy)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        ThemdichvuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfCM, tfName, tfPhong1});

        ThemdichvuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnThem, btnXoa});

        ThemdichvuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btDy, jButton3});

        pn.add(Themdichvu, "themdichvu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // get model of Jlist
        if (!b) {
            DefaultListModel<String> model = (DefaultListModel<String>) lstDV.getModel();
            // delete item is selected
            if (!model.isEmpty() && lstDV.getSelectedIndex() >= 0) {
                maDV.remove(lstDV.getSelectedIndex());
                model.remove(lstDV.getSelectedIndex());
                for (int i = 0; i < maDV.size(); i++) {
                    System.out.println(maDV.get(i) + " < mdv");
                }
            }
            // set model for JList
            lstDV.setModel(model);
            
            if(lstDV.getModel().getSize() == 0){
                btDy.setEnabled(false);
                btnXoa.setEnabled(false);
            }
                
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String dv = cb1.getSelectedItem().toString().trim();
        DefaultListModel<String> model;
        if (lstDV.getModel().getSize() == 0) {
            model = new DefaultListModel<>();
            btnXoa.setEnabled(true);
            b = false;
            btDy.setEnabled(true);
             btnXoa.setEnabled(true);
        } else {
            model = (DefaultListModel) lstDV.getModel();
        }

        model.addElement(dv);
        for (int i = 0; i < f.getDichVu().size(); i++) {
            if (dv.equalsIgnoreCase(f.getDichVu().get(i).getName())) {
                maDV.add(f.getDichVu().get(i).getId());
                lstDV.setModel(model);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btDyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDyActionPerformed
        //        ListModel model = lstDV.getModel();
        DataProcess db = new DataProcess();
        for (int i = 0; i < f.getHoaDon().size(); i++) {
            if (tfPhong.getText().trim().equalsIgnoreCase(f.getHoaDon().get(i).getMaPhong())) {
                makh = f.getHoaDon().get(i).getId();
            }
        }
        for (int i = 0; i < maDV.size(); i++) {
            db.addDichVu(makh, maDV.get(i));
        }
        JOptionPane.showMessageDialog(this, "Thêm dịch vụ thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btDyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (thoihan != -1) {
                String maPhong;
                long ngayNhan = 0;
                String sNgay = tfNgay.getText().trim();
                String TenKH = tfTen.getText().trim();

                String CMND = tfCmnd.getText().trim();
                String SDT = tfDT.getText().trim();
                long ngayTra = 0;

                try {
                    maPhong = tfPhong.getText();
                    if (!maPhong.equals("")) {
                        if (!TenKH.equals("")) {
                            if (!CMND.equals("") && v.checkNumber(CMND)) {
                                try {

                                    if (this.NgayTra == 0 && this.NgayNhan == 0) {
                                        ngayNhan = getLDate();
                                        if (!sNgay.equals("")) {
                                            int Ngay = 0;
                                            try {

                                                Ngay = Integer.parseInt(sNgay);

                                                long lngay = Ngay * 24 * 60 * 60 * 1000;
                                                ngayTra = ngayNhan + lngay;
                                                if (Ngay > thoihan && thoihan != 0) {
                                                    JOptionPane.showMessageDialog(this, "Chỉ có thể đặt nhỏ hơn " + thoihan + " ngày!", "Lỗi thời hạn!", JOptionPane.ERROR_MESSAGE);
                                                } else {
                                                    //Gọi hàm để đặt phòng
                                                    wel.f.setDateHoaDon(TenKH, CMND, SDT, maPhong, ngayNhan, ngayTra);
                                                    JOptionPane.showMessageDialog(this, "Đặt phòng " + maPhong + " thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                                    CardLayout c = (CardLayout) pn.getLayout();
                                                    tfPhong1.setText(tfPhong.getText().trim());
                                                    tfName.setText(tfTen.getText().trim());
                                                    tfCM.setText(tfCmnd.getText().trim());
                                                    c.show(pn, "themdichvu");
                                                }
                                            } catch (NumberFormatException | HeadlessException e) {
                                                JOptionPane.showMessageDialog(this, "Ngày nhập phải là số!", "Lỗi định dạnh số!", JOptionPane.ERROR_MESSAGE);
                                                System.out.println(e.toString());
                                            }

                                        } else {
                                            JOptionPane.showMessageDialog(this, "Ngày nhập không được bỏ trống!", "Lỗi định dạnh số!", JOptionPane.ERROR_MESSAGE);
                                        }
                                    } else {
                                        ngayTra = this.NgayTra;
                                        ngayNhan = this.NgayNhan;
                                        //Gọi hàm để đặt phòng
                                        wel.f.setDateHoaDon(TenKH, CMND, SDT, maPhong, ngayNhan, ngayTra);
                                        JOptionPane.showMessageDialog(this, "Đặt phòng " + maPhong + " thành công!");
                                        this.NgayNhan = 0;
                                        this.NgayTra = 0;
                                        CardLayout c = (CardLayout) pn.getLayout();

                                        tfPhong1.setText(tfPhong.getText().trim());
                                        tfName.setText(tfTen.getText().trim());
                                        tfCM.setText(tfCmnd.getText().trim());
                                        c.show(pn, "themdichvu");

                                    }

                                } catch (Exception e) {

                                    JOptionPane.showMessageDialog(this, "Ngày nhận trống hoặc không đúng định dạng ngày!", "Dữ liệu trống!", JOptionPane.ERROR_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "CMND trống hoặc không đúng định dạng!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Tên khách hàng không được bỏ trống!", "Dữ liệu trống!", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Số phòng không được bỏ trống!", "Lỗi định dạnh số!", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Mã phòng trống hoặc không phải là số!", "Lỗi!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Phòng đã có người đặt trước trong 24h tới!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNgayActionPerformed

    private String getDate() {
        Date d = new Date();
        SimpleDateFormat dinhDangThoiGian = new SimpleDateFormat("HH:mm dd/MM/yyyy");
        String t1 = dinhDangThoiGian.format(d.getTime());

        return t1;
    }

    private long getLDate() {
        Date d = new Date();
        return d.getTime();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dphong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dphong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dphong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dphong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dphong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Themdichvu;
    private javax.swing.JButton btDy;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JPanel datphong;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lbEndDAy;
    private javax.swing.JLabel lbNgayTra;
    private javax.swing.JLabel lbNofi;
    private javax.swing.JLabel lbtraphong2;
    private javax.swing.JList<String> lstDV;
    private javax.swing.JPanel pn;
    private javax.swing.JTextField tfCM;
    private javax.swing.JTextField tfCmnd;
    private javax.swing.JTextField tfDT;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNgay;
    private javax.swing.JTextField tfNgayNhan;
    private javax.swing.JTextField tfNgayTra;
    private javax.swing.JTextField tfPhong;
    private javax.swing.JTextField tfPhong1;
    private javax.swing.JTextField tfTen;
    // End of variables declaration//GEN-END:variables
}
